name: Release
on:
  push:
    tags:
    - v**

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-cli:
    strategy:
      matrix:
        include:
        - arch: linux-amd64
          runs-on: ubuntu-24.04
        - arch: linux-arm64
          runs-on: ubuntu-24.04-arm
        - arch: macos-amd64
          runs-on: macos-latest
        - arch: macos-arm64
          runs-on: macos-latest-xlarge
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Install just
        uses: extractions/setup-just@v1
      
      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          just build
          mkdir bin
          mv target/release/pruner bin/pruner-${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: pruner-${{ matrix.arch }}
          if-no-files-found: error
          path: bin/pruner-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: bin/pruner-${{ matrix.arch }}
          draft: true
